name: Test toast-conda
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-12
          - macos-11
          - macOS-10.15
    steps:
    - uses: actions/checkout@v3
    - name: Install mamba
      run: |
        wget https://github.com/ickc/reproducible-os-environments/raw/master/install/mamba.sh
        chmod +x mamba.sh
        ./mamba.sh
    - name: Install toast-conda
      run: |
        . "$HOME/.mambaforge/bin/activate"
        CONDA_PREFIX="$HOME/.mambaforge" bin/toast-conda.sh -p $HOME/.toast-conda
      env:
        # c.f. https://github.com/hpc4cmb/toast/blob/eb1e65097f99ecac63d8976f7131764a43a7ff07/src/toast/tests/runner.py#L113-L117
        CIBUILDWHEEL: 1
